### ISSUE TITLE
Restarting a game to day zero?

### ISSUE THREAD

**Issue by douglas24** [DaneelTrevize/TABSAT#3]
I'm not seeing any option to reset a save file to day zero even though the main TABSAT page says it's an option for trying another strategy?

**Comment by DaneelTrevize** [comment]
The app can automatically backup game saves, but it cannot trigger their generation.  
Saves cannot be modified so as to roll back time and restore killed zombies & their starting positions, such information is not present in the files.  
Save and exit a game at the start on day 0 to create that as a restore option in TABSAT.
