### ISSUE TITLE
Blank tabs

### ISSUE THREAD

**Issue by jeanbulinckx** [DaneelTrevize/TABSAT#5]
If the main windows fail to find the .exe path and none are supplied as the first argument a sequence of errors cannot load the tab controls and no message is reported for the user.

Suggestion: A nice dialog asking for the correct paths can make a better UX

**Comment by zrrx4444** [comment]
Thank you for reminding me need to add parameters

**Comment by zrrx4444** [comment]
> If the main windows fail to find the .exe path and none are supplied as the first argument a sequence of errors cannot load the tab controls and no message is reported for the user.
> 
> Suggestion: A nice dialog asking for the correct paths can make a better UX

Thank you for reminding me that we need to add parameters

**Comment by DaneelTrevize** [comment]
Steam library detection should be fixed by the new 1.4.0 release.
The previous failure to find TAB should have already been visible in the log UI.
