### ISSUE TITLE
Saves directory not located (Auto backup not working)

### ISSUE THREAD

**Issue by Chip-Chairman** [DaneelTrevize/TABSAT#6]
error:  The provided saves directory does not exist.

Also getting Antivirus warning on 1.4.x versions

**Comment by DaneelTrevize** [comment]
> The provided saves directory does not exist.

This message comes from [here](https://github.com/DaneelTrevize/TABSAT/blob/master/TABSAT/TABSAT/BackupsManager.cs#L179), ultimately supplied by [here](https://github.com/DaneelTrevize/TABSAT/blob/master/TABSAT/TABSAT/MainWindow.cs#L33), either the second commandline argument passed upon launch, or the result of the Windows environment expanding "%USERPROFILE%\Documents\My Games\They Are Billions\Saves\".  
Are you launching TABSAT with any script or shortcut passing arguments to it? If not, please try browsing to that path in Explorer. If it does not exist, have you generated any save files with this TAB install yet? Try creating a new skirmish game, then Save & Exit it and test again.

> Also getting Antivirus warning on 1.4.x versions

This is issue #4 , please confirm this is still occuring in 1.4.2 or higher, and which AV/ISS, and any more detailed warning, thank you.

**Comment by Chip-Chairman** [comment]
Thanks for the super fast feedback.

The path doesnt exist because ONeDrive inserts itself when I follow the path to the saves directory:
%userprofile%\ONeDrive\Documents\...

mklink /j "Documents" "%userprofile%\OneDrive\Documents"
Corrected that!

Now, for the TABSAT virus error.  I am using the built in Windows Defender;  v 1.4.3 is not having an issue.  Thanks for your help!

**Comment by DaneelTrevize** [comment]
> %userprofile%\ONeDrive\Documents

Interesting. Could you please run the following statement in PowerShell and paste the result, redacting your username if you wish:
`[Environment]::GetFolderPath("mydocuments")`

For my own note, there is potentially [the CSIDL_MYDOCUMENTS environmental variable](https://learn.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables) to use, and the newer [SpecialFolders](https://learn.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=netframework-4.8.1) Personal and MyDocuments.  
These could also avoid any localisation issue of "Documents" being e.g. "Dokumente".

Edit:
[This](https://github.com/DaneelTrevize/TABSAT/blob/81aece8cab722df19b08a172f5c4a0754876db54/TABSAT/TABSAT/bin/x64/Release/TABSAT.exe) latest build should work without needing that junction link for your OneDrive\Documents setup. Feel free to test it with the junction removed, if nothing else about your system now depends on that.

**Comment by Chip-Chairman** [comment]
Correct, C:\Users\<username>\OneDrive\Documents

**Comment by DaneelTrevize** [comment]
If you can, please retest using [version 1.4.4](https://github.com/DaneelTrevize/TABSAT/releases/tag/1.4.4) without that junction link in place.
